INSERT INTO COURSE (COURSE_NAME, COURSE_CODE, COURSE_DESCRIPTION, COURSE_ACTIVE)
	VALUES ('Advanced Java Programming', 'CSCI-3830', 'adv prog', 'TRUE');

--INSERT INTO CUSTOMER (NAME) VALUES ('Erik');	-- 1
--INSERT INTO CUSTOMER (NAME) VALUES ('Brad');	-- 2
--INSERT INTO CUSTOMER (NAME) VALUES ('Brian');	-- 3
--INSERT INTO CUSTOMER (NAME) VALUES ('Sydnie');	-- 4
--INSERT INTO CUSTOMER (NAME) VALUES ('Stacey');	-- 5
--INSERT INTO CUSTOMER (NAME) VALUES ('Emily');	-- 6
--
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('AMD', 13.49, 1);	-- 1
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('INTC', 35.27, 3);	-- 2
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('GOOGL', 872.37, 1);-- 3
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('AAPL', 139.91, 3);	-- 4
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('NVDA', 106.07, 2);	-- 5
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('FB', 139.84, 4);	-- 6
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('MSFT', 64.87, 5);	-- 7
--INSERT INTO STOCK (NAME, PRICE, RATING) VALUES ('AMZN', 852.31, 1);	-- 8