INSERT INTO COURSE (COURSE_NAME, COURSE_CODE, COURSE_DESCRIPTION, COURSE_CREDITS, COURSE_ACTIVE)
	VALUES ('Computer Science Principles', 'CSCI-1200', 'This course introduces students to the foundational principles of computer science. It aims to help students learn the essential thought processes used by computer scientists to solve problems, expressing those solutions as computer programs. The exercises and projects make use of mobile devices and other emerging platforms.', '3', 'TRUE'),
           ('Introduction to Computer Programming', 'CIST-1400', 'An introduction to programming within the context of a high level modern programming language. Coverage of fundamental programming concepts and program design; including arrays, user defined types, and objects. This course has an optional laboratory component in CIST 1404.', '3', 'TRUE'),
           ('Introduction to Computer Science II', 'CSCI-1620', 'Continuation of CIST 1400. Advanced topics in programming; topics in data representation and manipulation, data structures, problem solving and algorithm design.', '3', 'TRUE'),
           ('Introduction to C Programming', 'CSCI-2240', 'Programming in C in a UNIX operating system environment; algorithm and program development and file manipulation using C; UNIX-like utility development.', '3', 'TRUE'),
           ('Programming on the Internet', 'CSCI-2850', 'This course is an introduction to and overview of Internet-based application development focusing on the use of Java, Perl and other server-based programming languages. Software development in the context of the World Wide Web and other Internet services will be emphasized. Internet application development will also be discussed. Other techniques will be covered.', '3', 'TRUE'),
           ('Information Technology Ethics', 'CIST-3110', 'The course will cover the development and need for issues regarding privacy and the application of computer ethics to information technology.', '3', 'FALSE'),
           ('Advanced Java Programming', 'CSCI-3830', 'This course teaches students Web-based programming techniques in the Java programming language. It begins with programming using traditional models such as the client-server model and then transitions to advanced programming paradigms including middleware programming using RMI and CORBA, the distributed JINI/JavaSpaces model, the peer-to-peer networking model and the agent-based programming model.', '3', 'TRUE'),
           ('Principles of Programming Languages', 'CSCI-4220', 'This course covers the foundational concepts and principles underlying the design and implementation of programming languages. Language constructs including assignment, equality, references, aggregations, scope, encapsulation, and parameter passing are discussed. A central theme is how a particular language construct relates to the concept of equational reasoning (referential transparency). Formal notations for describing syntax and semantics are presented.', '3', 'TRUE'),
           ('Human-Computer Interaction', 'CSCI-4250', 'Human-computer interaction is concerned with the joint performance of tasks by humans and machines; human capabilities to use machines (including learnability of interfaces); algorithms and programming of the interface; engineering concerns that arise in designing and building interfaces; the process of specification, design, and implementation of interfaces; and design trade-offs.', '3', 'TRUE'),
           ('Introduction to Software Engineering', 'CSCI-4830', 'Basic concepts and major issues of software engineering, current tools and techniques providing a basis for analyzing, designing, developing, maintaining and evaluating software systems. Technical, administrative and operating issues. Privacy, security and legal issues.', '3', 'TRUE'),
           ('Internet Systems Development', 'CSCI-4900', 'This course focuses on contemporary techniques and technologies in the design, development, and integration of web-enabled information systems. This is a rapidly moving, hands-on course that mirrors real-world development of internet-based applications.', '3', 'TRUE'),
           ('English Composition I', 'ENGL-1150', 'Instruction and practice in academic literacy practices, especially writing summaries, analyses, and critical essays in response to assigned texts.', '3', 'TRUE'),
           ('English Composition II', 'ENGL-1160', 'Instruction and practice in academic inquiry, especially researching, analyzing, and writing arguments.', '3', 'TRUE'),
           ('Principles of Accounting I', 'ACCT-2010', 'Basic concepts and assumptions underlying financial accounting; basic structure of accounting, the accounting cycle, external financial statements of the enterprise with emphasis on the corporation; income determination, accounting for and reporting of assets, liabilities and owners equity, analysis and reporting of cash flows, financial statement analysis.', '3', 'TRUE'),
           ('Introduction to Neuroscience', 'NEUR-1500', 'This course is designed for neuroscience majors or students who are contemplating neuroscience as a major. The course will explore how individual neurons operate, how collections of neurons integrate with each other, and how larger scale collections lead to the expression of behavior, emotion, and cognition.', '3', 'TRUE'),
           ('Calculus I', 'MATH-1950', 'This is a course in plane analytic geometry emphasizing the study of functions, limits, derivatives and applications, and an introduction to integration.', '5', 'TRUE'),
		   ('Calculus II', 'MATH-1960', 'This course introduces applications of integration, techniques of integration, infinite sequences and series, vectors in the plane, and polar functions. A mathematical software package is introduced, with required assignments.', '5', 'FALSE');
		   
INSERT INTO ROLE (ROLE_ID, NAME)
	VALUES (1, 'ROLE_USER'), (2, 'ROLE_ADMIN');